### ISSUE TITLE
Nested Binding

### ISSUE THREAD

**Issue by patrickcorrigan** [vuejs/vuefire#754] opened 2020-05-18 09:51 UTC
I'm building a comment system using Vuefire. 
I'm trying to recursively resolve child comments. 
It works one level deep for rending to the HTML but any more than that the reactive doesn't seem to update. I'm not sure if this is the correct way to do it. I'm trying to $bind to properties of an object I've already used $bind on. Is this possible? Here is my code. Note level isn't used yet but it was how I was going to limit the depth.

``` js
    async resolveChildComments(comments, level, template) {
      for (let idx = 0; idx < 1 && comments.length; idx++) {
        let comment = comments[idx];
        console.log('level', level, 'comment', comment, 'idx', idx, 'children', comment.children, template)
        const parent = db.collection('comments').doc(comment.id);
        await this.$bind(`${template}.${idx}.children`, db.collection('comments').where('parent', '==', parent).orderBy('rating', 'desc').orderBy('meta.createdAt', 'desc'));
        await this.resolveChildComments(comments[idx].children, level + 1, `${template}.${idx}.children`)
      }
    }


 await this.resolveChildComments(this.selectedPostComments, 0, 'selectedPostComments');
```

**Comment by posva** [comment] 2020-05-18 10:41
Duplicate of https://github.com/vuejs/vuefire/issues/153

**Closed by posva** 2020-05-18 10:41 UTC
