### ISSUE TITLE
Rebinding collection resets data in property to empty array

### ISSUE THREAD

**Issue by Mirakurun** [vuejs/vuefire#298] opened 2019-07-05 23:14 UTC
Hello,

I've noticed that whenever I rebind my collection to my data property, the data resets to an empty array, then a split second later the data populates with data from my collection.  This is causing an issue with my data table rendering from populated to empty then to populated.  

I tried the { reset: false } option, but that doesn't help in this situation because the resetting happens during the binding.

Is there a way to rebind a collection without resetting my data?

**Comment by posva** [comment] 2019-07-06 09:49
Duplicate of https://github.com/vuejs/vuefire/issues/83

**Closed by posva** 2019-07-06 09:49 UTC
