### ISSUE TITLE
Can't bind document with sub references without opening the firestore rules

### ISSUE THREAD

**Issue by tralves** [vuejs/vuefire#295] opened 2019-06-30 12:35 UTC
Using `nativescript-plugin-firebase` by @eddyerburgh.

I have a `categories` collection. Each category has an array (not a collection) of references to`recipe`.

I am creating the binding like this: 

```
return bindFirestoreRef("categories", db.collection("categories"), { maxRefDepth: 1 });
```

In Firestore, I have the rules:

```
    match /categories/{document=**} {
      allow read, update: if request.auth.uid != null;
    }

    match /recipes/{document=**} {
      allow read, update: if request.auth.uid != null;
    }
```

In this situation, the binding will not work (`bindFirestoreRef` will never resolve). I don't see any errors in the console, even with a `catch`.

This problem is related to the rules not being applied to the sub-references.

It *does* work if I do one of the following:

1- I change the binding to `{ maxRefDepth: 0 }` because it will not grab the sub-documents. 

2- If I open the firestore rules with 
  ```
    match /{document=**} {
      allow read, update: if request.auth.uid != null;
    }
   ```

This is very weird because I am also binding the recipes and that works with the original rules! For this reason, I think it has something to do with the way Vuexfire is binding sub-references.

Sorry, I can't dig deeper right now. Maybe I am doing something wrong?

**Comment by posva** [comment] 2019-06-30 13:58
I would say Vuefire is binding nested ref but rules are preventing it. The weird thing is there is no access error. Are you running a minified version of Firebase? Even though I think they report errors

**Comment by posva** [comment] 2019-06-30 14:02
In that case, this would be a duplicate of https://github.com/vuejs/vuefire/issues/281

**Comment by tralves** [comment] 2019-06-30 14:07
Thank you for the quick reply. I saw that issue too, but I don't think they are the same. In that situation, the reference was to a doc that was not allowed. In my case, the referenced document (e.g `/recipes/1`) has the proper rules, since I am binding it too with:

``` 
  return bindFirestoreRef("recipes", db.collection("recipes"));
```

and it works. Testing again. Could be cache or something.

Later today I will give this another shot. I just wanted to make sure it was not a known issue.

**Comment by posva** [comment] 2019-06-30 15:02
Ah yeah, it seems to be different indeed. However, I don't know where it's coming from. My guess is there is something with the SDK. If you have a repro with the JS SDK, I can take a look!

**Comment by posva** [comment] 2019-07-25 07:07
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.

**Closed by posva** 2019-07-25 07:07 UTC
Labels: need repro
