### ISSUE TITLE
Invalid value for option "firebase": expected an Object, but got Function.

### ISSUE THREAD

**Issue by p4m** [vuejs/vuefire#133] opened 2017-10-14 09:18 UTC
It seems that after the upgrade to the latest Vue and Vuefire version, Firebase can not be used with the Function call. I use this all the time, because of the ability of passing a value in the 'where clause', callback function (for setting loading status and in some cases performing data manipulation).

Created a new project using the latest vue-cli (2.9.1), moved my source of an existing project to this new project to check what I have to change/improve.

###  versions

    "firebase": "^4.5.1",
    "vue": "^2.4.2",
    "vue-router": "^2.7.0",
    "vuefire": "^1.4.4"
    "vue-loader": "^13.0.4",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.4.2",
    "webpack": "^3.6.0",

### Error (after upgrade)

![image](https://user-images.githubusercontent.com/1651685/31574429-fc93dd5a-b0cf-11e7-8c69-f31d61608bbc.png)

Is this a bug?

**Comment by posva** [comment] 2017-10-14 20:17
It's a false alarm. You can use a function for the `firebase` property. The warning shouldn't appear

**Comment by p4m** [comment] 2017-10-14 22:40
I created a new clean project and imported Firebase and VueFire.
No luck, got the error. As soon as I do the 'normal' call, no error occurs.
Please tell me that you don't have the same issue.

![image](https://user-images.githubusercontent.com/1651685/31579918-58998020-b141-11e7-8dcb-cf06e1bd3ff8.png)

![image](https://user-images.githubusercontent.com/1651685/31579882-90436514-b140-11e7-9a12-6155c35a770a.png)

**Comment by posva** [comment] 2017-10-15 12:13
Don't worry about the error, it will work 🙂

**Comment by mi1971** [comment] 2017-10-16 22:08
Hey @posva , Even though this still works, can it (or will it) be fixed to prevent unnecessary warnings in the console. Or...can we actually pass an object instead of a function?

**Comment by posva** [comment] 2017-10-17 11:58
Objects and functions both work. Don't mind the error, it should be removed in the future

**Comment by llavre** [comment] 2017-10-31 08:29
Uh... Already wasted few hours with this error and in final found this issue. It must be fixed. :)

**Comment by react-rails** [comment] 2017-11-28 02:37
@posva 
Can you please let us know when this issue will be fixed?

**Comment by posva** [comment] 2017-11-28 07:35
Just subscribe to the issue and you'll be notified when the issue is fixed 😉

**Closed** 2017-12-04 23:55 UTC
Labels: enhancement

**Comment by dylancarlone** [comment] 2017-12-28 09:07
I'm getting blocked by this warning when using the firestore branch. It seems when the firestore property is a function, it is never executed.

**Comment by posva** [comment] 2017-12-28 16:16
@dylancarlone it should be working but I may have not released it yet. Can you try building it yourself?

**Comment by dylancarlone** [comment] 2017-12-28 20:16
@posva any chance you'll be releasing it soon? I'm having the hardest time setting up the branch locally. Thanks for such a quick response!

**Comment by posva** [comment] 2017-12-28 21:40
@dylancarlone I actually did, I think 2 hours ago 😆 
That's weird, it should as easy as `npm i && npm run build` but you should be able to test with the latest release

**Comment by dylancarlone** [comment] 2017-12-28 22:39
My mistake, I should have checked the releases first. Everything is working great. Thank you very much!
