### ISSUE TITLE
vuefire@next doesn't work on Vue 3

### ISSUE THREAD

**Issue by khteh** [vuejs/vuefire#1225] opened 2022-02-13 07:15 UTC
### Reproduction
```
$ n i vuefire@next --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myapp@2021.11.24
npm ERR! Found: vue@3.2.31
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.29" from @quasar/app@3.3.3
npm ERR!   node_modules/@quasar/app
npm ERR!     dev @quasar/app@"^3.3.3" from the root project
npm ERR!   peer vue@"3.2.31" from @vue/server-renderer@3.2.31
npm ERR!   node_modules/@vue/server-renderer
npm ERR!     @vue/server-renderer@"3.2.31" from vue@3.2.31
npm ERR!   2 more (vue-router, vuex)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! vuefire@"3.0.0-alpha.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 3" from @vue/composition-api@1.4.6
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peer @vue/composition-api@"^1.0.0-beta.1" from vuefire@3.0.0-alpha.2
npm ERR!     node_modules/vuefire
npm ERR!       vuefire@"3.0.0-alpha.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/khteh/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2022-02-13T07_12_58_726Z-debug-0.log
```
Use one of the examples at https://github.com/vuejs/vuefire/tree/master/packages/vuefire/examples to boil down and reproduce the problem. If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look

### Actual behavior

A clear and concise description of what actually happens.

**Comment by posva** [comment] 2022-02-13 13:52
Duplicate of  #1072

**Closed as completed by posva** 2022-02-13 13:52 UTC

**Comment by khteh** [comment] 2022-02-20 06:04
https://github.com/vuejs/vuefire/issues/898
