### ISSUE TITLE
Using `.key` in track-by throws error

### ISSUE THREAD

**Issue by syropian** [vuejs/vuefire#5] opened 2016-04-15 02:36 UTC
When trying to track by `.key` I get the following error:

`[Vue warn]: Invalid expression. Generated function body: .key`

Template code:

```
<ul>
  <li v-for="guest in guests" track-by=".key">{{ guest.name }}</li>
</ul>
```

Edit: I also tried wrapping `.key` in single quotes, eg:

```
  <li v-for="guest in guests" track-by="'.key'">{{ guest.name }}</li>
```

but that began throwing duplicate value errors.

**Comment by yyx990803** [comment] 2016-04-15 03:25
Ah, a change recently introduced in Vue 1.0.21 caused this error... it is now fixed in the dev branch, and will be out in the next release (soon). In the meanwhile you can either downgrade to 1.0.20, or build Vue core from the dev branch yourself.

Sorry about that!

**Comment by weislanes** [comment] 2016-04-15 06:27
I'm seeing the same problem so I downgraded to 1.0.20 as suggested. This stopped the duplicate warning appearing however now duplicate data shows whenever I update Firebase. 

I'm using Sortable drag and drop and when I move an item from one list to another I use a directive triggered on dragend to set the items list property to the new list.  This was working before the switch to Vuefire. I'd update the item property passed in the directive:

` v-updatelist="task.list" `
`destList = $(this.el).closest("ul").attr("data-list"); //get destination list`
` this.set(destList); //set list property of this item to the destination list`

then update Firebase:

`new Firebase(baseTasks + "/" + draggedID).update({
                list: destList,
            }, onComplete);`

I've removed updating the Vue data (this.set) as Vuefire should handle the binding but can't get this to work now as duplicates appear each time I drag and drop. I don't see any mention of using update in your docs so wondering whether this is supported or if simply going about it in the wrong way?

**Comment by yyx990803** [comment] 2016-04-15 18:01
@weislanes do you have a way to reproduce the issue you described? If yes please open a separate issue with the repro.

**Comment by weislanes** [comment] 2016-04-15 18:41
@yyx990803 I'm currently trying to reproduce and looks like it may be an issue with the layout of slots in my app structure. Will raise separately if persists after I change a few things.  :+1:

**Comment by jwngr** [comment] 2016-05-31 20:57
Closing since this issue is a bit stale and it's not clear it is an issue with the actual VueFire library. If you are still having issues, let us know and we can re-open.

**Closed by jwngr** 2016-05-31 20:57 UTC
Labels: bug
