### ISSUE TITLE
Data should not be reset on initial $bind

### ISSUE THREAD

**Issue by andrewspy** [vuejs/vuefire#347] opened 2019-08-22 08:11 UTC
I noticed that data always get reset on initial $bind, which creates a flash before $bind is completed if there are existing data. I understand there is option set `reset` behavior in subsequent $bind, but for the initial bind, data should be left intact until the $bind is completed.

**Comment by posva** [comment] 2019-08-22 08:25
Duplicate of https://github.com/vuejs/vuefire/issues/83

**Closed by posva** 2019-08-22 08:25 UTC
