### ISSUE TITLE
Document with references can produce permissions error

### ISSUE THREAD

**Issue by hugo082** [vuejs/vuefire#373] opened 2019-09-08 17:10 UTC
When you bind a document that contains reference to another document, VueFire try to load nested documents.

### Problem

If user have not access to referenced document,  Firebase produce `FirebaseError: Missing or insufficient permissions` error.

Maybe we can provide an option to disable this feature or just catch firebase error and ignore nested bind for this reference ?

**Comment by posva** [comment] 2019-09-09 07:37
Duplicate of https://github.com/vuejs/vuefire/issues/281

**Closed by posva** 2019-09-09 07:37 UTC
