### ISSUE TITLE
Upgrade to Firebase v8

### ISSUE THREAD

**Issue by JFGHT** [vuejs/vuefire#951] opened 2020-11-19 08:49 UTC
### Steps to reproduce the behavior

Simply use vuefire/vuexfire with Firebase v8.

### Expected behavior

Everything working fine.

### Actual behavior

Error in many files (types).

> Error in node_modules/@posva/vuefire-core/dist/packages/@posva/vuefire-core/src/firestore/index.d.ts(3,10):
> Module '"../../../../../../../../firebase"' has no exported member 'firestore'. Did you mean to use 'import firestore from "../../../../../../../../firebase"' instead?
>  > 3 | import { firestore } from 'firebase';

**Comment by posva** [comment] 2020-11-19 09:15
Duplicate of https://github.com/vuejs/vuefire/pull/940

---

Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2020-11-19 09:15 UTC
