### ISSUE TITLE
Suport for new Firestore

### ISSUE THREAD

**Issue by ebertti** [vuejs/vuefire#148] opened 2017-11-20 14:49 UTC
Hi,

Firebase relaease a new service called Firestore, with a new way to store data.

https://firebase.google.com/docs/firestore/?hl=pt-br

The vuefire team has some plans to make a bind to that too?

**Comment by posva** [comment] 2017-11-20 14:59
Duplicate of #145 😉 
Next time check at least the issues first 😛

**Closed by posva** 2017-11-20 14:59 UTC
