### ISSUE TITLE
No Firebase App

### ISSUE THREAD

**Issue by ahmedragab20** [vuejs/vuefire#1407] opened 2023-08-13 15:35 UTC
### Reproduction

Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).

### Steps to reproduce the bug

1) create an app with nuxt version of 3.6.5
2) install all the required dependencies for the app according to https://vuefire.vuejs.org/nuxt/getting-started.html
3) try to use `getAuth()` utility from firebase

### Expected behavior

expected to be working fine on SSR

### Actual behavior

sometimes it works fine, and sometimes the app gets stuck with an error of Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app).
-------------------------------------------------------
at Module.getAuth (./node_modules/.pnpm/@firebase+auth@1.1.0_@firebase+app@0.9.15_react-native@0.72.3/node_modules/@firebase/auth/dist/node-esm/totp-04ac595e.js:6595:24)
at setup (./pages/auth/signup.js:23:40)
at _sfc_main.setup (./pages/auth/signup.js:94:23)
at callWithErrorHandling (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
at setupStatefulComponent (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7190:25)
at setupComponent (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7151:36)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:614:15)
at renderVNode (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:743:14)
at renderComponentSubTree (./node_modules/.pnpm/@vue+server-renderer@3.3.4_vue@3.3.4/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:698:7)

### Additional information

packge.json:
"devDependencies": {
    "firebase-admin": "^11.10.1",
    "firebase-functions": "^4.4.1",
    "nuxt": "^3.6.5"
  },
  "dependencies": {
    "@firebase/app-types": "^0.9.0",
    "firebase": "^10.1.0",
    "nuxt-vuefire": "^0.2.13",
    "vuefire": "^3.1.13"
  }

---------------------------------------------------------------------------
  
  nuxt.config (all variables are fine):
    modules: ['@nuxthq/ui', 'nuxt-vuefire'],
    vuefire: {
    auth: true,
    config: {
      apiKey: config.API_KEY,
      authDomain: config.AUTH_DOMAIN,
      projectId: config.PROJECT_ID,
      appId: config.APP_ID,
      measurementId: config.MEASUREMENT_ID,
      messagingSenderId: config.MESSAGING_SENDER_ID,
    },
    admin: {
      serviceAccount: config.ADMIN_SERVICE,
    },
  },

**Comment by posva** [comment] 2023-08-13 18:53
Make sure you also added the credentials, that could be the issue. You also need to use useFirebaseAuth() and other composables like shown in docs so the right app is used 

Closing due to the missing reproduction

**Closed** 2023-08-13 18:53 UTC

**Comment by ahmedragab20** [comment] 2023-08-13 21:01
Thank you so much @posva ❤️
