### ISSUE TITLE
Not compatible with lru-cache >= 9.0.0

### ISSUE THREAD

**Issue by mklueh** [vuejs/vuefire#1348] opened 2023-04-14 06:58 UTC
### Reproduction

https://github.com/vuejs/vuefire/discussions/1346

### Steps to reproduce the bug

Having lru-cache > 9.0.0 in your project will break this module

### Expected behavior

...

### Actual behavior

Previous issue has been moved to discussions for whatever reason, see https://github.com/vuejs/vuefire/discussions/1346

**Comment by posva** [comment] 2023-04-14 07:19
Duplicate of https://github.com/vuejs/vuefire/discussions/1346

**Closed by posva** 2023-04-14 07:19 UTC

**Comment by posva** [comment] 2023-04-14 07:21
Please do not create duplicates like this, it really wastes my time as a maintainer. I sometimes need more time to reply but I eventually get back to people 🙂 .
